package de.orchound;

import java.io.PrintWriter;
import java.util.stream.Stream;

public class ConfigFormatter {

	private final static String GENERATOR_MESSAGE = "// Generated by Quake Config Formatter";
	private final EntriesFormatter bindings = new EntriesFormatter();
	private final EntriesFormatter aliases = new EntriesFormatter();

	private boolean clearBindings = false;
	private boolean clearAliases = false;

	public ConfigFormatter(Stream<String> source) {
		source.forEach(line -> {
			if (line.matches("^bind .+")) {
				bindings.addEntry(line);
			} else if (line.matches("^set.? .+")) {
				aliases.addEntry(line);
			} else if (line.equals("unbindall")) {
				clearBindings = true;
			} else if (line.equals("unaliasall")) {
				clearAliases = true;
			}
		});
	}

	public void format(PrintWriter writer) {
		writer.println(GENERATOR_MESSAGE);
		writer.println();
		printBindings(writer);
		writer.println();
		printVariables(writer);
	}

	private void printHeader(String caption, PrintWriter writer) {
		writer.println(String.format("--- %s ---", caption));
		writer.println();
	}

	private void printBindings(PrintWriter writer) {
		printHeader("Bindings", writer);

		if (clearBindings)
			writer.println("unbindall");

		bindings.print(writer);
	}

	private void printVariables(PrintWriter writer) {
		printHeader("Variables", writer);

		if (clearAliases)
			writer.println("unaliasall");

		aliases.print(writer);
	}
}
