package de.orchound;

import java.io.PrintWriter;
import java.util.*;
import java.util.stream.Stream;

public class ConfigFormatter {

	private final static String GENERATOR_MESSAGE = "// Generated by Quake Config Formatter";
	private final Set<String> bindings = new TreeSet<>();
	private final Set<String> aliases = new TreeSet<>();

	private boolean clearBindings = false;
	private boolean clearAliases = false;

	public ConfigFormatter(Stream<String> source) {
		source.forEach(line -> {
			if (line.startsWith("bind")) {
				bindings.add(line);
			} else if (line.startsWith("seta")) {
				aliases.add(line);
			} else if (line.equals("unbindall")) {
				clearBindings = true;
			} else if (line.equals("unaliasall")) {
				clearAliases = true;
			}
		});
	}

	public void format(PrintWriter writer) {
		writer.println(GENERATOR_MESSAGE);
		writer.println();
		printBindings(writer);
		writer.println();
		printAliases(writer);
	}

	private void printHeader(String caption, PrintWriter writer) {
		writer.println("// -------------------");
		writer.println(String.format("// --- %s", caption));
		writer.println("// -------------------");
		writer.println();
	}

	private void printBindings(PrintWriter writer) {
		printHeader("Bindings", writer);

		if (clearBindings)
			writer.println("unbindall");

		for (String binding : bindings)
			writer.println(binding);
	}

	private void printAliases(PrintWriter writer) {
		printHeader("Aliases", writer);

		if (clearAliases)
			writer.println("unaliasall");

		for (String alias : aliases)
			writer.println(alias);
	}
}
